# Generated by Django 6.0.2 on 2026-02-10 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bluebus', '0002_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='booking',
        ),
    ]
